### ISSUE TITLE
Functional interface

### ISSUE THREAD

**Issue by rkern** [zoj613/polya-gamma#4]
Instead of subclassing `Generator`, I recommend implementing `polyagamma(rng, h, z)` as a top-level function that takes a `Generator` as an argument. That will make it easier to integrate into existing codebases that are already passing around `np.random.Generator` instances. This is how we envisioned most such third-party distributions being implemented.

This is just a recommendation that you are welcome to ignore. However, it is something that I would be looking for when this code gets contributed to `scipy.stats`.

**Comment by zoj613** [comment]
Thanks @rkern for suggestion. I am open to changing the API to be more usable with other libraries. I think it is a good idea and I will follow through with your suggestion. I have one minor concern though. What about users who are not familiar with the `Generator` interface, who just want to pass `h` and `z` and get a sample? Is there a way to make it easy for them to be able to use the distribution without being bothered to create their own instances of a `rng` everytime?

**Comment by rkern** [comment]
I would probably use the conventions that most other functions that consume a `Generator` use: take it as an optional argument and use `np.random.default_rng()` to cast it to a `Generator`. It defaults to creating a fresh `Generator` with OS-derived entropy, but you can also pass in a seed number/sequence, or the `Generator` instance you are already using.

```python
def polyagamma(h, z, random_state=None):
    rng = np.random.default_rng(random_state)
    ...
```

Most functions in `scipy` and `scikit-learn` usually name this argument `random_state` and use a conversion function called `check_random_state()`, because they started doing this with the old `RandomState` code. `default_rng()` is built to satisfy basically the same needs as `check_random_state()` but with `Generator`, of course. Because you've expressed interest in this getting into `scipy.stats` (where we'd want consistency with the conventions used in the `rvs()` methods), I'm going to recommend calling it that. But if you're more interested in this module standing alone, I'd probably call it `rng` or something like that.

**Comment by zoj613** [comment]
> I would probably use the conventions that most other functions that consume a `Generator` use: take it as an optional argument and use `np.random.default_rng()` to cast it to a `Generator`. It defaults to creating a fresh `Generator` with OS-derived entropy, but you can also pass in a seed number/sequence, or the `Generator` instance you are already using.
> 
> ```python
> def polyagamma(h, z, random_state=None):
>     rng = np.random.default_rng(random_state)
>     ...
> ```
> 
> Most functions in `scipy` and `scikit-learn` usually name this argument `random_state` and use a conversion function called `check_random_state()`, because they started doing this with the old `RandomState` code. `default_rng()` is built to satisfy basically the same needs as `check_random_state()` but with `Generator`, of course. Because you've expressed interest in this getting into `scipy.stats` (where we'd want consistency with the conventions used in the `rvs()` methods), I'm going to recommend calling it that. But if you're more interested in this module standing alone, I'd probably call it `rng` or something like that.

Ahh, okay I see. I'm familiar with the random_state kwarg from `scikit-learn`. I am planning on releasing version 0.1.0 to PyPI since the majority of the work is complete. I will switch to the functional interface after I have added the saddle point sampling method, which is the only thing left to do. Does the creation of the Generator instance every function call have any performance implications?

**Comment by rkern** [comment]
Some, but it's not especially large and it's always fixable by passing in your own `Generator`, so I don't worry about it.

**Comment by zoj613** [comment]
@rkern I was wondering if you have any advise regarding https://github.com/zoj613/polyagamma/issues/47 ? Basically, I want to expose the C-API functions so they can be cimportable in third party cython modules. When I tried this by having a `__init__.pxd` file, python raised errors about not being able to find the symbol for the `pgm_random_polyagamma` function. Strangely, It was able find symbols for and cimport the `sampler_t` enum and the other two static functions in the [header](https://github.com/zoj613/polyagamma/blob/main/include/pgm_random.h). I am a little confused as to why this is happening, since I don't have much experience with C.
